### ISSUE TITLE
Correct spelling error in name of repo

### ISSUE THREAD

**Issue by bnvk** [OpenTechFund/CryptoTermininology#1]
Perhaps I mistaken, but it seems the name of this repo itself is misspelled. In the title of the README you have `Crypto Terminology` but the repo title seems to have an extra "in" and is spelled `CryptoTermininology`

**Comment by tomrittervg** [comment]
Hah! I don't know if I misspelled it in my email to @danblah or he did it.  (Probably me.)  In any event he will have to rename it.

**Comment by danblah** [comment]
Ha! Done :)
